//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviesAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movy
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Category { get; set; }
        public string Director { get; set; }
        public string FirstStar { get; set; }
        public int YearReleased { get; set; }
    }
}
